<?php

/**
 * @file
 *   Provides suggestions for tags to add to Facebook-style Statuses.
 */

/**
 * Implementation of hook_menu().
 */
function fbssts_menu() {
  $items = array();
  $items['admin/settings/fbssts'] = array(
    'title' => 'Facebook-style Statuses Tag Suggestions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fbssts_admin'),
    'access arguments' => array('administer site configuration'),
    'description' => 'Allows administrators to adjust certain display settings for Facebook-style Statuses Tag Suggestions.',
    'file' => 'fbssts.admin.inc',
  );
  $items['fbssts/load'] = array(
    'title' => 'Load suggestions',
    'page callback' => '_fbssts_autocomplete',
    'access arguments' => array('use tag suggestions'),
    'description' => 'Gets the HTML for use in the floating tag suggestion dialog.',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function fbssts_perm() {
  return array('use tag suggestions');
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function fbssts_form_facebook_status_box_alter(&$form, &$form_state) {
  if (!user_access('use tag suggestions')) {
    return;
  }
  $path = drupal_get_path('module', 'fbssts');
  drupal_add_js($path .'/fbssts.js');
  drupal_add_css($path .'/fbssts.css');
  $form['fbssts'] = array(
    '#value' => '<div class="fbssts-suggestions" style="display: none;"></div>',
    '#weight' => 1000,
  );
}

/**
 * Implementation of hook_theme().
 */
function fbssts_theme($existing, $type, $theme, $path) {
  return array(
    'fbssts' => array(
      'arguments' => array(
        'part' => NULL,
        'type' => NULL,
      ),
    ),
  );
}

/**
 * Themes autocompleted suggestions.
 */
function theme_fbssts($type, $part) {
  $suggestions = fbssts_get_suggestions($type, $part, variable_get('fbssts_count', 5));
  $items = array();
  foreach ($suggestions as $item) {
    $items[] = check_plain($item->name);
  }
  return theme('item_list', $items, NULL, 'ul', array('class' => 'fbssts-suggestion-list'));
}

function fbssts_get_suggestions($type, $part, $count) {
  $s = _fbssts_get_suggestions($type, $part, $count, TRUE);
  if (count($s) < $count) {
    $t = $type == 'term' ?
      _fbssts_get_suggestions($type, $part, $count, FALSE, $s) :
      _fbssts_get_all_user_suggestions($part, $count, $s);
    $s = array_merge($s, $t);
  }
  return $s;
}

function _fbssts_get_suggestions($type, $part, $count, $own, $exclude = array()) {
  $where = array("t.type = '%s'", "t.name LIKE '%s%%'");
  $args = array($type, $part);
  if (variable_get('fbssts_time', 604800)) {
    $where[] = "f.created > %d";
    $args[] = time() - variable_get('fbssts_time', 604800);
  }
  if ($own) {
    $where[] = "f.sender = %d";
    $args[] = $GLOBALS['user']->uid;
  }
  if ($exclude) {
    $ids = array();
    foreach ($exclude as $item) {
      if ($item->type == $type) {
        $ids[] = $item->id;
      }
    }
    if ($ids) {
      $where[] = "t.rid NOT IN (". db_placeholders($ids) .")";
      $args = array_merge($args, $ids);
    }
  }
  $result = db_query_range("
    SELECT COUNT(t.sid) count, t.rid, t.name
    FROM {facebook_status_tags} t
    INNER JOIN {facebook_status} f
      ON t.sid = f.sid
    WHERE ". implode(" AND ", $where) ."
    GROUP BY t.rid
    ORDER BY count DESC, t.name DESC
  ", $args, 0, $count);
  $suggestions = array();
  while ($obj = db_fetch_object($result)) {
    $suggestions[] = (object) array(
      'type' => $type,
      'id' => $obj->rid,
      'name' => $obj->name,
    );
  }
  return $suggestions;
}

function _fbssts_get_all_user_suggestions($part, $count, $exclude) {
  $args = array($part);
  $ex = "";
  if ($exclude) {
    $ids = array();
    foreach ($existing as $item) {
      if ($item->type == 'user') {
        $ids[] = $item->id;
      }
    }
    if ($ids) {
      $ex = "AND u.uid NOT IN (". db_placeholders($ids) .")";
      $args = array_merge($args, $ids);
    }
  }
  $result = db_query_range("
    SELECT 'user' AS type, uid, name
    FROM {users}
    WHERE LOWER(name) LIKE LOWER('%s%%') $ex
    ORDER BY name ASC
  ", $args, 0, $count);
  $s = array();
  while ($account = db_fetch_object($result)) {
    $s[] = $account;
  }
  return $s;
}

/**
 * Helper function to autocomplete tags.
 */
function _fbssts_autocomplete() {
  $text = $_POST['text'];
  $part = _fbssts_find_tag($text);
  $length = drupal_strlen($part);
  $result = _fbssts_clean_tag($part);
  $part = $result['tag'];
  $prefix = $result['prefix'];
  if ($part) {
    echo '<span class="fbssts-hidden fbssts-part-length">'. $length .'</span>'. theme('fbssts', $prefix == '#' ? 'term' : 'user', $part);
  }
}

/**
 * Searches for tags in a string.
 *
 * Tags can be in the following formats:
 *   - #hashtag
 *   - @userreference
 *   - [#tag with word-break characters]
 *
 * @param $subject
 *   The text in which to replace tags.
 * @return
 *   A nested array of tags. The outer array is keyed by type ('@' and '#').
 */
function _fbssts_find_tag($subject) {
  $pattern = '%((?:\A|(?<=\s))(?:#|@)(\w|(\p{L}\p{M}?))+$)|(\[(#|@)[^\]]+?(?!\])$)%u';
  if (variable_get('facebook_status_tags_alt_pattern', FALSE)) {
    $pattern = '%((?:\A|(?<=\s))(?:#|@)\w+$)|(\[(#|@)[^\]]+?(?!\])$)%u';
  }
  $matches = array();
  preg_match_all($pattern, $subject, $matches);
  if (!empty($matches[0])) {
    $word = array_pop($matches[0]);
    return $word;
  }
}

/**
 * Removes leading #, @, [#, or [@ from a tag.
 * @param $tag
 *   The tag to clean.
 * @return
 *   An associative array with the clean tag ('tag') and the prefix ('prefix').
 */
function _fbssts_clean_tag($tag) {
  $one = drupal_substr($tag, 0, 1);
  if ($one == '[') {
    $prefix = drupal_substr($tag, 1, 1);
    $tag = drupal_substr($tag, 2);
  }
  else {
    $prefix = $one;
    $tag = drupal_substr($tag, 1);
  }
  return array('tag' => $tag, 'prefix' => $prefix);
}
